# Generated by Django 5.2.17 on 2026-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOCUMENTO_RECIBIDO', 'Documentación Recibida'), ('SOLICITUD_PRESENTADA', 'Solicitud Presentada'), ('PAGO_REALIZADO', 'Pago / Gasto Realizado'), ('RESPUESTA_RECIBIDA', 'Respuesta / Notificación Recibida'), ('DOCUMENTO_SOLICITADO', 'Documentación Solicitada al Cliente'), ('REUNION', 'Reunión / Llamada'), ('CAMBIO_ESTADO', 'Cambio de Estado de Asunto'), ('OTRO', 'Otra Actividad / Nota')], default='OTRO', max_length=40)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título o Resumen de Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada de lo ocurrido')),
                ('fecha_actividad', models.DateField(verbose_name='Fecha del suceso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Bitácora / Actividad',
                'verbose_name_plural': 'Bitácora de Actividades',
                'ordering': ['-fecha_actividad', '-created_at'],
            },
        ),
    ]
