# Generated by Django 5.2.17 on 2026-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('ci_nit', models.CharField(db_index=True, max_length=50, verbose_name='CI / NIT')),
                ('tipo_cliente', models.CharField(choices=[('EMPRESA', 'Empresa / Persona Jurídica'), ('INDIVIDUAL', 'Persona Natural / Individual')], default='EMPRESA', max_length=20)),
                ('empresa_relacionada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa Relacionada')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono / Celular')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
