# Generated by Django 5.2.17 on 2026-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FONDO_RECIBIDO', 'Fondo Recibido del Cliente'), ('GASTO_FONDO_CLIENTE', 'Gasto con Fondo del Cliente'), ('GASTO_PROPIO', 'Gasto Propio (Pendiente Reembolso)'), ('REEMBOLSO_RECIBIDO', 'Reembolso Recibido'), ('DEVOLUCION_SALDO', 'Devolución de Saldo al Cliente')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto / Razón del gasto o ingreso')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('moneda', models.CharField(default='BOB', max_length=10, verbose_name='Moneda')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('QR', 'Pago QR / Móvil'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Detalle')),
                ('reembolsado', models.BooleanField(default=False, verbose_name='¿Reembolsado?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_financieros', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
