# Generated by Django 5.2.17 on 2026-10-02 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('procesos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Pagado / Registrado por'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='procesos.procesoasunto', verbose_name='Proceso / Asunto'),
        ),
    ]
