# Generated by Django 5.2.17 on 2026-10-02 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('finanzas', '0002_initial'),
        ('procesos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo',
            field=models.CharField(choices=[('FONDO_RECIBIDO', 'Fondo Recibido del Cliente'), ('PAGO_CUOTA_HONORARIO', 'Pago de Cuota / Honorario'), ('GASTO_FONDO_CLIENTE', 'Gasto con Fondo del Cliente'), ('GASTO_PROPIO', 'Gasto Propio (Pendiente Reembolso)'), ('REEMBOLSO_RECIBIDO', 'Reembolso Recibido'), ('DEVOLUCION_SALDO', 'Devolución de Saldo al Cliente')], max_length=30, verbose_name='Tipo de Movimiento'),
        ),
        migrations.CreateModel(
            name='CuotaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de Cuota')),
                ('monto_esperado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la Cuota (Bs)')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Efectivamente Pagado (Bs)')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('comprobante_o_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia / N° Recibo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuota de Pago',
                'verbose_name_plural': 'Cuotas de Pago',
                'ordering': ['plan', 'numero_cuota'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.cuotapago', verbose_name='Cuota Vinculada'),
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Honorario / Plan')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total (Bs)')),
                ('numero_cuotas', models.IntegerField(default=1, verbose_name='Número de Cuotas')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso / Pagando'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='EN_CURSO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='clientes.cliente', verbose_name='Cliente')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_pago', to='procesos.procesoasunto', verbose_name='Asunto / Proceso')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago en Cuotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cuotapago',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='finanzas.planpago', verbose_name='Plan de Pago'),
        ),
    ]
