# Generated by Django 5.2.17 on 2026-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoAsunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del asunto / proceso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción detallada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('ESPERANDO_DOCUMENTACION', 'Esperando documentación'), ('ESPERANDO_CLIENTE', 'Esperando cliente'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Proceso / Asunto',
                'verbose_name_plural': 'Procesos y Asuntos',
                'ordering': ['-created_at'],
            },
        ),
    ]
