# Generated by Django 5.2.17 on 2026-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('RECIBO', 'Recibo'), ('TICKET', 'Ticket / Vale'), ('BOLETA_DEPOSITO', 'Boleta de Depósito'), ('COMPROBANTE_TRANSFERENCIA', 'Comprobante de Transferencia / QR'), ('OTRO', 'Otro')], default='FACTURA', max_length=30)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Factura / Recibo')),
                ('proveedor_emisor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor / Razón Social Emisor')),
                ('nit_emisor', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIT / CI Emisor')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('concepto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Concepto / Detalle')),
                ('imagen', models.ImageField(upload_to='comprobantes/%Y/%m/', verbose_name='Imagen / Fotografía')),
                ('ocr_procesado', models.BooleanField(default=False)),
                ('datos_extraidos_ia', models.JSONField(blank=True, null=True, verbose_name='Datos Extraídos por IA / OCR')),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('VERIFICADO', 'Verificado / Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
