# Generated by Django 5.2.17 on 2026-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título / Nombre del documento')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato'), ('COMPROBANTE', 'Comprobante'), ('INFORME', 'Informe'), ('ESCANEO', 'Escaneo'), ('FOTOGRAFIA', 'Fotografía'), ('NOTA', 'Nota'), ('LEGAL', 'Documento Legal / Trámite'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Archivo')),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Notas')),
                ('fecha_documento', models.DateField(blank=True, null=True, verbose_name='Fecha del Documento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.categoriadocumento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
