# Generated by Django 5.2.17 on 2026-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='procesos.procesoasunto', verbose_name='Proceso / Asunto'),
        ),
    ]
