# Generated by Django 5.2.17 on 2026-10-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='texto_extraido',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Extraído del Archivo'),
        ),
    ]
