# Generated by Django 5.2.17 on 2026-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('INFORME_GESTION', 'Informe de Gestión General'), ('INFORME_FINANCIERO', 'Estado de Cuenta / Gastos'), ('INFORME_PROCESOS', 'Resumen de Procesos y Asuntos'), ('INFORME_IA', 'Informe Especial Asistido por IA')], default='INFORME_GESTION', max_length=40)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='Contenido / Markdown / Resumen')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='informes_pdf/%Y/%m/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_generados', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Informe Generado',
                'verbose_name_plural': 'Informes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
